import { ContentTemplate, ContentType } from './types';

/**
 * Template generator for fallback content when AI is unavailable
 */
export class TemplateService {
    private static _instance: TemplateService;

    public static getInstance(): TemplateService {
        if (!TemplateService._instance) {
            TemplateService._instance = new TemplateService();
        }
        return TemplateService._instance;
    }

    public generateTemplate(type: string, data: { topic: string; context?: string; domain: string }): string {
        const contentType = type.replace('-', '_') as ContentType;
        return this._generateByType(contentType, data.topic, data.domain);
    }

    private _generateByType(type: ContentType, topic: string, domain: string): string {
        switch (type) {
            case 'chapter_outline':
                return this._getChapterOutlineTemplate(topic, domain);
            case 'lesson_content':
                return this._getLessonContentTemplate(topic, domain);
            case 'exercise':
                return this._getExerciseTemplate(topic, domain);
            case 'quiz':
                return this._getQuizTemplate(topic, domain);
            case 'summary':
                return this._getSummaryTemplate(topic, domain);
            default:
                throw new Error(`Unknown content type: ${type}`);
        }
    }

    private _getChapterOutlineTemplate(topic: string, domain: string): string {
        return `# Chapter Outline: ${topic}

## Domain: ${domain}

### Learning Objectives
- Understand the fundamentals of ${topic}
- Apply key concepts in practical scenarios
- Identify best practices and common pitfalls

### Chapter Structure

#### 1. Introduction
- What is ${topic}?
- Why is it important in ${domain}?
- Overview of what you'll learn

#### 2. Core Concepts
- Key terminology
- Fundamental principles
- How it works

#### 3. Practical Applications
- Real-world examples
- Use cases in ${domain}
- Step-by-step implementations

#### 4. Best Practices
- Dos and don'ts
- Common mistakes to avoid
- Professional recommendations

#### 5. Advanced Topics
- Complex scenarios
- Integration with other concepts
- Future considerations

#### 6. Summary and Next Steps
- Key takeaways
- Action items
- Further learning resources

### Assessment
- Knowledge check questions
- Practical exercises
- Project assignments

---
*Generated by Book Writing Assistant*
`;
    }

    private _getLessonContentTemplate(topic: string, domain: string): string {
        return `# Lesson: ${topic}

## Introduction

Welcome to this lesson on **${topic}** in the context of ${domain}. By the end of this lesson, you will have a solid understanding of the key concepts and be able to apply them in real-world scenarios.

## What You'll Learn

- Core concepts of ${topic}
- Practical applications in ${domain}
- Best practices and common patterns
- Hands-on examples

## Core Concepts

### Definition
${topic} is a fundamental concept in ${domain} that involves...

### Key Components
1. **Component 1**: Description and importance
2. **Component 2**: How it relates to the overall concept
3. **Component 3**: Practical considerations

## Practical Examples

### Example 1: Basic Implementation
\`\`\`
// Example code or step-by-step process
Step 1: Initial setup
Step 2: Core implementation
Step 3: Testing and validation
\`\`\`

### Example 2: Advanced Usage
\`\`\`
// More complex example
Advanced implementation details
\`\`\`

## Best Practices

- ✅ **Do**: Follow these recommended approaches
- ❌ **Don't**: Avoid these common mistakes
- 💡 **Tip**: Professional insights and shortcuts

## Common Challenges

### Challenge 1: [Common Issue]
**Problem**: Description of the issue
**Solution**: How to address it
**Prevention**: How to avoid it in the future

## Summary

In this lesson, we covered:
- The fundamentals of ${topic}
- How it applies to ${domain}
- Practical implementation strategies
- Best practices for success

## Next Steps

1. Practice with the provided exercises
2. Explore additional resources
3. Apply concepts to your own projects

---
*Generated by Book Writing Assistant*
`;
    }

    private _getExerciseTemplate(topic: string, domain: string): string {
        return `# Exercises: ${topic}

## Domain: ${domain}

### Exercise 1: Basic Understanding
**Objective**: Test your foundational knowledge of ${topic}

**Instructions**:
1. Review the core concepts
2. Complete the following tasks:
   - Task A: [Specific instruction]
   - Task B: [Specific instruction]
   - Task C: [Specific instruction]

**Expected Outcome**: You should be able to demonstrate basic understanding

### Exercise 2: Practical Application
**Objective**: Apply ${topic} concepts to a real-world scenario

**Scenario**: You are working on a ${domain} project that requires...

**Your Task**:
1. Analyze the requirements
2. Design a solution using ${topic}
3. Implement your approach
4. Document your process

**Deliverables**:
- Solution design document
- Implementation code/steps
- Reflection on challenges faced

### Exercise 3: Problem Solving
**Objective**: Troubleshoot and optimize

**Problem Statement**: Given a scenario where ${topic} is not working as expected...

**Your Challenge**:
1. Identify the root cause
2. Propose solutions
3. Implement the best approach
4. Test and validate

### Self-Assessment

Rate your understanding (1-5 scale):
- [ ] Core concepts of ${topic}
- [ ] Practical applications
- [ ] Problem-solving abilities
- [ ] Confidence in implementation

### Additional Practice

For more practice:
1. Create your own examples
2. Explore edge cases
3. Research advanced techniques
4. Share with peers for feedback

---
*Generated by Book Writing Assistant*
`;
    }

    private _getQuizTemplate(topic: string, domain: string): string {
        return `# Quiz: ${topic}

## Domain: ${domain}

### Instructions
- Answer all questions to the best of your ability
- Review your answers before submitting
- Use this as a learning tool to identify areas for improvement

---

### Multiple Choice Questions

**Question 1**: What is the primary purpose of ${topic} in ${domain}?
- [ ] A) Option A
- [ ] B) Option B
- [ ] C) Option C
- [ ] D) Option D

**Question 2**: Which of the following is a best practice for ${topic}?
- [ ] A) Option A
- [ ] B) Option B
- [ ] C) Option C
- [ ] D) Option D

### True/False Questions

**Question 3**: ${topic} is essential for all ${domain} applications.
- [ ] True
- [ ] False

**Question 4**: The main benefit of ${topic} is improved performance.
- [ ] True
- [ ] False

### Short Answer Questions

**Question 5**: Explain in your own words what ${topic} means in the context of ${domain}.

_Your answer:_


**Question 6**: Describe a real-world scenario where ${topic} would be particularly important.

_Your answer:_


### Practical Questions

**Question 7**: Given the following scenario, how would you apply ${topic}?

*Scenario description...*

_Your solution:_


---

## Answer Key

### Multiple Choice
1. **C** - Explanation of why this is correct
2. **B** - Explanation of why this is correct

### True/False
3. **False** - Explanation
4. **True** - Explanation

### Short Answer (Sample Responses)
5. A good answer should include: key concepts, practical applications, importance in domain
6. Examples might include: specific use cases, industry applications, problem-solving scenarios

### Practical (Evaluation Criteria)
7. Look for: understanding of concepts, practical approach, consideration of constraints

---
*Generated by Book Writing Assistant*
`;
    }

    private _getSummaryTemplate(topic: string, domain: string): string {
        return `# Summary: ${topic}

## Domain: ${domain}

### Key Concepts

**Main Definition**: ${topic} is...

**Core Principles**:
1. **Principle 1**: Brief explanation
2. **Principle 2**: Brief explanation
3. **Principle 3**: Brief explanation

### Important Terms

| Term | Definition |
|------|------------|
| Term 1 | Explanation of the term |
| Term 2 | Explanation of the term |
| Term 3 | Explanation of the term |

### Practical Applications

- **Use Case 1**: Where and how it's applied
- **Use Case 2**: Benefits and considerations
- **Use Case 3**: Real-world examples

### Best Practices Checklist

- ✅ Always remember to...
- ✅ Consider the impact of...
- ✅ Validate your approach by...
- ❌ Avoid doing...
- ❌ Don't forget to...

### Common Pitfalls

1. **Pitfall 1**: What to watch out for
2. **Pitfall 2**: How to prevent it
3. **Pitfall 3**: Warning signs

### Action Items

After learning about ${topic}, you should:

**Immediate Next Steps**:
- [ ] Practice with basic examples
- [ ] Review core concepts
- [ ] Complete exercises

**Short-term Goals** (1-2 weeks):
- [ ] Apply to a small project
- [ ] Explore advanced features
- [ ] Seek feedback from peers

**Long-term Development** (1+ months):
- [ ] Master advanced techniques
- [ ] Teach others
- [ ] Contribute to community resources

### Further Learning

**Recommended Resources**:
- Books: [Suggested reading]
- Online Courses: [Course recommendations]
- Documentation: [Official docs and guides]
- Communities: [Forums and discussion groups]

### Quick Reference

**Essential Commands/Steps**:
\`\`\`
// Quick reference for implementation
Key steps or code snippets
\`\`\`

---

### Reflection Questions

1. How will you apply ${topic} in your work?
2. What aspects need more practice?
3. What questions do you still have?

---
*Generated by Book Writing Assistant*
`;
    }
}
